targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          build_extensions:
            "^lib/{{}}.dart": "lib/generated/{{}}.g.dart"
      freezed:
        options:
          build_extensions:
            "^lib/{{}}.dart": "lib/generated/{{}}.freezed.dart"
      slang_build_runner:
        options:
          base_locale: ja
          input_directory: i18n
          input_file_pattern: .i18n.json
          output_directory: "lib/generated/i18n"
          string_interpolation: double_braces
          namespaces: true
          translate_var: i18n
